BusinessMVC2/Controllers/NationalAccountController.cs
using BusinessData;
using BusinessModels.Franchise;
using BusinessModels;
using BusinessServices;
using Microsoft.AspNet.Identity;
using SelectPdf;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessModels.NationalAccount;
using BusinessData.Interfaces;

namespace BusinessMVC2.Controllers
{
    public class NationalAccountController : Controller
    {
        private readonly NationalAccountService _nationalAccountService;

        public NationalAccountController(NationalAccountService accountService)
        {
            _nationalAccountService = accountService;
        }


        // GET: NationalAccount
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var accounts = _nationalAccountService.GetNationalAccounts();

            var model = accounts.ToList().Select(f => new AccountListItem
            {
                AccountId = f.AccountId,
                AccountName = f.AccountName,
                // Add other properties as needed
            });

            return View(model);
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AccountCreate model)
        {
            if (ModelState.IsValid)
            {
                return View(model);
            }
            var userId = Guid.Parse(User.Identity.GetUserId());
            _nationalAccountService.CreateNationalAccount(model);

            return RedirectToAction("Index");
        }

        //GET: Details
        //NationalAccount/Details/{id}
        public ActionResult Details(int id)
        {
            var accountId = id;
            var model = _nationalAccountService.GetClientsByNationalAccountId(id);
            return View(model);
        }


        //GET: Edit
        //NationalAccount/Edit/{id}
        public ActionResult Edit(int id)
        {
            var detail = _nationalAccountService.GetNationalAccountById(id);
            var model = new AccountEdit
            {
                AccountId = detail.AccountId,
                AccountName = detail.AccountName,
                State = detail.State,
            };
            return View(model);
        }

        //POST: Edit
        //NationalAccount/Edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, AccountEdit model)
        {
            var currentUserId = User.Identity.GetUserId();
            if (!ModelState.IsValid) return View(model);


            if (model.AccountId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }


            if (_nationalAccountService.UpdateNationalAccount(model))
            {
                TempData["SaveResult"] = "Your National Account has been updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your National Account could not be updated.");
            return View(model);
        }

        //GET: Delete
        //NationalAccount/Delete/{id}
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var model = _nationalAccountService.GetNationalAccountById(id);
            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteNationalAccount(int id)
        {

            // Update the IsActive field of the Franchise instead of deleting it
            _nationalAccountService.DeleteNationalAccount(id);

            TempData["SaveResult"] = "Your National Account has been marked as inactive.";

            return RedirectToAction("Index");
        }


        // GET: List
        // NationalAccount/List/{id}
        public ActionResult List(int id)
        {
            var clients = _nationalAccountService.GetClientsByNationalAccountId(id);
            var model = clients.Clients.Select(c => new BusinessListItem
            {
                BusinessId = c.BusinessId,
                BusinessName = c.BusinessName,
                FranchiseName = c.Franchise.FranchiseName,
                AccountName = c.NationalAccount.AccountName,
                FacilityID = c.FacilityID,
                Address = c.Address,
                City = c.City,
                State = c.State,
                ZipCode = c.ZipCode,
                OwnerId = c.OwnerId,
            });

            // Retrieve the National Account name using the service method or any other way
            var nationalAccountName = _nationalAccountService.GetNationalAccountById(id)?.AccountName;

            // Pass the National Account name to the ViewBag
            ViewBag.NationalAccountName = nationalAccountName;

            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SubmitAction(FormCollection collection)
        {
            // read parameters from the webpage
            string userId = collection["UserId"];
            Guid userGuid = Guid.Parse(userId);
            int accountId = Convert.ToInt32(collection["AccountId"]);

            var account = _nationalAccountService.GetNationalAccountById(accountId);

            // Calculate the total CO2 saved for the franchise
            double totalCO2Saved = _nationalAccountService.GetTotalCO2SavedForFranchiseById(accountId);
            int states = _nationalAccountService.CountDistinctStatesWithClientsByFranchiseId(accountId);
            int locations = _nationalAccountService.CountClientsByFranchiseId(accountId);
            account.Locations = locations;
            account.TotalCO2Saved = totalCO2Saved;
            account.StateReach = states;

            // generate JavaScript to hide the navbar
            string script = "function hideNavbar(){var e=document.getElementsByClassName('navbar')[0];if(e){e.style.display='none';}}; hideNavbar();";

            // generate HTML code for the business details and inject JavaScript to hide the navbar
            string htmlString = RenderViewToString(ControllerContext, "~/Views/NationalAccount/AccountDetailsToPdf.cshtml", account, script);


            // instantiate a html to pdf converter object
            HtmlToPdf converter = new HtmlToPdf();

            string pdfPageSize = collection["DdlPageSize"];
            PdfPageSize pageSize = (PdfPageSize)Enum.Parse(typeof(PdfPageSize), pdfPageSize, true);

            string pdfOrientation = collection["DdlPageOrientation"];
            PdfPageOrientation pdfOrientationEnum = (PdfPageOrientation)Enum.Parse(typeof(PdfPageOrientation), pdfOrientation, true);

            int webPageWidth = 1024;
            try
            {
                webPageWidth = Convert.ToInt32(collection["TxtWidth"]);
            }
            catch
            {
            }

            int webPageHeight = 0;
            try
            {
                webPageHeight = Convert.ToInt32(collection["TxtHeight"]);
            }
            catch
            {
            }

            // set converter options
            converter.Options.PdfPageSize = pageSize;
            converter.Options.PdfPageOrientation = pdfOrientationEnum;
            converter.Options.WebPageWidth = webPageWidth;
            converter.Options.WebPageHeight = webPageHeight;

            // create a new pdf document converting an url
            PdfDocument doc = converter.ConvertHtmlString(htmlString, "https://businessmvc220230407125015.azurewebsites.net/");

            // save pdf document
            byte[] pdf = doc.Save();

            // close pdf document
            doc.Close();

            // return resulted pdf document
            FileResult fileResult = new FileContentResult(pdf, "application/pdf");
            fileResult.FileDownloadName = "Document.pdf";

            // Pass the total CO2 saved value to the viewbag to be displayed in the PDF
            ViewBag.TotalCO2Saved = totalCO2Saved;

            return fileResult;
        }




        protected string RenderRazorViewToString(string viewName, object model)
        {
            ViewData.Model = model;
            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);
                return sw.GetStringBuilder().ToString();
            }
        }


        // helper method to render view to string
        private string RenderViewToString(ControllerContext context, string viewName, object model, string script)
        {
            ViewEngineResult result = ViewEngines.Engines.FindView(context, viewName, null);
            if (result.View == null)
            {
                throw new FileNotFoundException("View cannot be found.");
            }

            string viewData = "";
            using (var sw = new StringWriter())
            {
                var viewContext = new ViewContext(context, result.View, new ViewDataDictionary(model), new TempDataDictionary(), sw);
                result.View.Render(viewContext, sw);

                // Add the JavaScript code to the end of the HTML body
                var html = sw.ToString();
                html = html.Replace("</body>", $"<script>{script}</script></body>");

                viewData = html;
            }

            return viewData;
        }

    }
}

BusinessMVC2/Views/NationalAccount/AccountDetailsToPDF.cshtml
@model BusinessModels.NationalAccount.AccountDetails


<head>
    <meta charset="utf-8" />
    <title>National Account Details to PDF</title>

    <style type="text/css">
        /* Styles for the PDF view */
        .certificate-container {
            max-width: 900px;
            margin: 0 auto;
            padding: 30px;
            border: 2px solid #333;
            font-family: 'Montserrat', sans-serif;
            background: #ffffff;
            z-index: -100;
        }

        .certificate-header {
            text-align: center;
        }

            .certificate-header h1 {
                font-size: 36px;
                font-weight: bold;
                margin: 0;
            }

        .certificate-body {
            margin: 40px 0;
        }

        .certificate-franchise-info h2 {
            font-size: 24px;
            font-weight: bold;
            margin: 0;
        }

        .certificate-franchise-info p {
            font-size: 16px;
            margin: 5px 0;
        }

        .certificate-savings-info p {
            font-size: 20px;
            margin: 20px 0;
        }

        .certificate-signature p {
            font-size: 16px;
            margin: 0;
            text-align: right;
            position: relative;
        }

        .certificate-signature h4 {
            font-size: 16px;
            margin: 0;
            text-align: right;
            position: relative;
            font-weight: bold;
        }

        #logo-container {
            position: relative;
            width: 100%;
            height: 200px;
            margin-top: 50px;
        }

        #trinity-logo img {
            position: absolute;
            max-width: 300px;
            left: 20px;
            bottom: 0;
            opacity: 0.75;
        }

        #gold-badge img {
            max-width: 200px;
            margin-top: 20px;
            position: absolute;
            right: 0px;
            bottom: 0;
            opacity: 0.75;
        }
    </style>

    <script type="text/javascript">
        // Hide the navigation bar when the page is loaded in the PDF
        window.onload = function () {
            var navBar = document.getElementById("navbar");
            navBar.style.display = "none";
        };
    </script>
</head>

<body>
    <div class="certificate-container">
        <div class="certificate-header">
            <h1>Certificate of Emissions Savings</h1>
        </div>
        <div class="certificate-body">
            <div class="certificate-franchise-info">
                <h2>@Model.AccountName</h2>
                <br />

            </div>
            <div class="certificate-savings-info">
                <p>Congratulations! Your franchise has saved @Model.TotalCO2Saved.ToString("N2") tons of CO2 emissions across @Model.Locations locations in @Model.StateReach State(s) by using our products and services. Keep up the great work!</p>

            </div>
            <div id="logo-container">
                <div id="trinity-logo">
                    <img src="https://businessmvc220230407125015.azurewebsites.net/Content/Images/Trinity Logo.png" alt="trinity-logo">
                </div>
                <div class="certificate-signature">
                    <p>Signed by:</p>
                    <h4>Smash My Trash</h4>
                    <div id="gold-badge">
                        <img src="https://businessmvc220230407125015.azurewebsites.net/Content/Images/SMT-Gold-Badge.png" alt="signature">
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

BusinessMVC2/Views/NationalAccount/Create.cshtml
@model BusinessModels.NationalAccount.AccountCreate

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Create National Account</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.HiddenFor(model => model.OwnerId, htmlAttributes: new { @class = "control-label col-md-2" })
               
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.AccountName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AccountName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AccountName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

BusinessMVC2/Views/NationalAccount/Delete.cshtml
@model BusinessModels.NationalAccount.AccountDetails

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>AccountDetails</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.AccountId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AccountId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AccountName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AccountName)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

BusinessMVC2/Views/NationalAccount/Details.cshtml
@model BusinessModels.NationalAccount.AccountDetails
@using Microsoft.AspNet.Identity;
@{
    double totalCO2Saved = 0;
    double gallons = 0;
    double coal = 0;
    double vehicle = 0;
    double smartphones = 0;
    double dieselSaved = 0; 

    foreach (var client in Model.Clients)
    {
        totalCO2Saved += client.TotalCO2SavedV2;
    }
    gallons = (float)(totalCO2Saved / 19.64);
    coal = (float)(totalCO2Saved / 2);
    vehicle = (float)(totalCO2Saved / .88);
    smartphones = (float)(totalCO2Saved / .02);
    dieselSaved = (float)(totalCO2Saved / 22.38); // Calculation for diesel saved
}

@{
    ViewBag.Title = "Details";
}

<h2>National Account - @Model.AccountName</h2>

<div>
    <h4></h4>
    <hr />
    <dl>
    </dl>

    @if (Model.Clients.Any())
    {
        <h3></h3>

        <table id="emissions">
            <tr>
                <th>Business Name</th>
                <th>Facility</th>
                <th>Emissions Saved (lbs)</th>
            </tr>
            @foreach (var client in Model.Clients)
            {
                <tr>
                    <td>@client.BusinessName</td>
                    <td>@client.FacilityID</td>
                    <td>@client.TotalCO2SavedV2.ToString("N2")</td>
                </tr>
            }
            <tr>
                <td>Total CO2 Saved Across All Clients for this Franchise</td>
                <td></td>
                <td><strong>@totalCO2Saved.ToString("N2")</strong></td>
            </tr>
        </table>
    }
    else
    {
        <p>No clients found.</p>
    }
    <br />

    <table id="emissions">
        <tr>
            <th>CO2 Equivalencies</th>
            <th>Values</th>
        </tr>
        <tr>
            <td>Gallons of gas not consumed</td>
            <td>@gallons.ToString("N2")</td>
        </tr>
        <tr>
            <td>Pounds of Coal not burned</td>
            <td>@coal.ToString("N2")</td>
        </tr>
        <tr>
            <td>Miles driven by the average passenger vehicle</td>
            <td>@vehicle.ToString("N2")</td>
        </tr>
        <tr>
            <td>Smartphones Charged</td>
            <td>@smartphones.ToString("N2")</td>
        </tr>
        <tr>
            <td>Gallons of diesel not consumed</td>
            <td>@dieselSaved.ToString("N2")</td>
        </tr>
    </table>

    <br />
</div>
@using (Html.BeginForm("SubmitAction", "NationalAccount", new { id = Model.AccountId }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <label for="TxtUrl"></label>
        <input type="hidden" name="TxtUrl" id="TxtUrl" class="form-control" value="https://businessmvc220230407125015.azurewebsites.net/NationalAccount/AccountDetailsToPdf/@Model.AccountId" required />
    </div>

    <input type="hidden" name="DdlPageSize" value="Letter" />
    <input type="hidden" name="DdlPageOrientation" value="Landscape" />
    <input type="hidden" name="TxtWidth" value="1024" />
    <input type="hidden" name="TxtHeight" value="0" />
    <input type="hidden" name="AccountId" value="@Model.AccountId" />
    @Html.Hidden("UserId", User.Identity.GetUserId())

    <button type="submit" class="btn btn-primary">
        Generate PDF
    </button>
}


<p>
    @Html.ActionLink("Back to List", "Index")
</p>

BusinessMVC2/Views/NationalAccount/Edit.cshtml
@model BusinessModels.NationalAccount.AccountEdit


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>AccountEdit</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.HiddenFor(model => model.AccountId, htmlAttributes: new { @class = "control-label col-md-2" })
    
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.AccountName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AccountName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AccountName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

BusinessMVC2/Views/NationalAccount/Index.cshtml
@model IEnumerable<BusinessModels.NationalAccount.AccountListItem>


<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>

<body>
    <h2>National Accounts</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AccountId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccountName)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AccountId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccountName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.AccountId }) |
                @Html.ActionLink("Details", "Details", new { id = item.AccountId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.AccountId }) |
                @Html.ActionLink("Client List", "List", new { id = item.AccountId })
            </td>
        </tr>
    }
    
    </table>
</body>

BusinessMVC2/Views/NationalAccount/List.cshtml
@model IEnumerable<BusinessModels.BusinessListItem>

@{
    ViewBag.Title = "List";
    var nationalAccountName = ViewBag.NationalAccountName as string; // Cast it to the correct type
}

<h2>@(nationalAccountName ?? "NA") Client List</h2>


<p>
    @Html.ActionLink("Create New", "Create", "Client")
</p>

<table id="clientsTable" class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.AccountName)</th>
            <th>@Html.DisplayNameFor(model => model.BusinessName)</th>
            <th>@Html.DisplayNameFor(model => model.City)</th>
            <th>@Html.DisplayNameFor(model => model.State)</th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.AccountName)</td>
                <td>@Html.DisplayFor(modelItem => item.BusinessName)</td>
                <td>@Html.DisplayFor(modelItem => item.City)</td>
                <td>@Html.DisplayFor(modelItem => item.State)</td>

                <td>
                    @Html.ActionLink("Edit", "Edit", "Client", new { id = item.BusinessId }, null) |
                    @Html.ActionLink("Details", "Details", "Client", new { id = item.BusinessId }, null) |
                    @Html.ActionLink("Delete", "Delete", "Client", new { id = item.BusinessId }, null)
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#clientsTable').DataTable();
        });
    </script>
}