BusinessMVC2/Controllers/ClientController.cs
using BusinessData;
using BusinessData.Enum;
using BusinessData.Interfaces;
using BusinessModels;
using BusinessMVC2.Models;
using BusinessServices;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Auth.OAuth2.Mvc;
using Google.Apis.Sample.MVC4;
using Google.Apis.Services;
using Google.Apis.Sheets.v4;
using Google.Apis.Sheets.v4.Data;
using Google.Apis.Util.Store;
using log4net;
using Microsoft.AspNet.Identity;
using SelectPdf;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace BusinessMVC2.Controllers
{

    public class ClientController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IUserIdProvider _userIdProvider;
        private readonly FranchiseService _franchiseService;
        private readonly NationalAccountService _nationalAccountService;
        private readonly ClientService _clientService;


        public ClientController(
            ApplicationDbContext context,
            IUserIdProvider userIdProvider,
            FranchiseService franchiseService,
            NationalAccountService nationalAccountService,
            ClientService clientService)
        {
            _context = context;
            _userIdProvider = userIdProvider;
            _franchiseService = franchiseService;
            _nationalAccountService = nationalAccountService;
            _clientService = clientService;
        }

        private static readonly ILog Log = LogManager.GetLogger(typeof(Client));

        // GET: Clients
        public ActionResult Index(string searchString)
        {
            //var franchises = _context.Franchises.Include(f => f.Clients).AsQueryable();
            var franchises = _context.Franchises.Include(f => f.Clients).Include(f => f.Roles).AsQueryable();

            // Temporarily hardcode the user's email for testing
            //string email = "susan.schlaack@smashmytrash.com"; // Replace with the actual user's email


            string email = User.Identity.Name;

            var businessesQuery = _clientService.GetBusinesses().AsQueryable();

            if (email != "doug.revell@smashmytrash.com")
            {
                var names = email.Split('@')[0].Split('.');
                var formattedName = string.Join(" ", names.Select(name => char.ToUpper(name[0]) + name.Substring(1)));

                // Abbreviation map
                Dictionary<string, string> abbreviations = new Dictionary<string, string>()
                {
                    { "Jonathan", "Jon" },
                    {"James","Jim" },
                    {"Matthew", "Matt" },

                    // add more abbreviations as needed
                };

                // Check if first name is in the abbreviation map, if so replace with full name
                var firstFormattedName = formattedName.Split(' ')[0];
                if (abbreviations.ContainsKey(firstFormattedName))
                {
                    formattedName = formattedName.Replace(firstFormattedName, abbreviations[firstFormattedName]);
                }

                // Fetch franchises based on owner names
                var ownerFranchises = franchises.Where(f => f.Owner1.Trim() == formattedName ||
                                                             f.Owner2.Trim() == formattedName ||
                                                             f.Owner3.Trim() == formattedName ||
                                                             f.Owner4.Trim() == formattedName);

                // Fetch franchises based on role emails
                var roleFranchises = franchises.Where(f => f.Roles.Any(role => role.Email.Trim().Equals(email, StringComparison.OrdinalIgnoreCase)));

                // Debugging: Print out the fetched franchises for inspection
                foreach (var franchise in roleFranchises)
                {
                    Console.WriteLine($"Franchise ID: {franchise.FranchiseId}, Franchise Name: {franchise.FranchiseName}");
                    foreach (var role in franchise.Roles)
                    {
                        Console.WriteLine($"-- Role: {role.Role}, Email: {role.Email}");
                    }
                }


                // Combine both lists, removing duplicates
                var combinedFranchises = ownerFranchises.Union(roleFranchises).ToList();
                // Debugging: Print out combined franchises
                Console.WriteLine("Combined Franchises:");
                foreach (var franchise in combinedFranchises)
                {
                    Console.WriteLine($"Franchise ID: {franchise.FranchiseId}, Franchise Name: {franchise.FranchiseName}");
                }

                // Get all client ids associated with these franchises
                var clientIds = combinedFranchises.SelectMany(f => f.Clients.Select(c => c.BusinessId)).ToList();

                // Filter businesses to only those owned by the franchises
                businessesQuery = businessesQuery.Where(b => clientIds.Contains(b.BusinessId));


            }

            if (!String.IsNullOrEmpty(searchString))
            {
                businessesQuery = businessesQuery.Where(b => b.BusinessName.Contains(searchString));
            }

            var businesses = businessesQuery
                .OrderBy(b => b.BusinessName)
                .ToList();

            return View(businesses);
        }



        public ActionResult Create()
        {
            ViewBag.Franchises = _franchiseService.GetFranchises().Select(f => new
            {
                FranchiseId = f.FranchiseId,
                FranchiseName = f.FranchiseName,
            }).ToList();

            ViewBag.NationalAccounts = _nationalAccountService.GetNationalAccounts().Select(f => new
            {
                AccountId = f.AccountId,
                AccountName = f.AccountName,
            });

            return View();
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BusinessCreate model)
        {
            if (!ModelState.IsValid) // Check if the ModelState is NOT valid
            {
                // Make sure the Franchises list is set correctly
                ViewBag.Franchises = _franchiseService.GetFranchises().Select(f => new
                {
                    FranchiseId = f.FranchiseId,
                    FranchiseName = f.FranchiseName
                }).ToList();

                ViewBag.NationalAccounts = _nationalAccountService.GetNationalAccounts().Select(f => new
                {
                    AccountId = f.AccountId,
                    AccountName = f.AccountName,
                });

                return View(model); // Return the view with the same model when ModelState is invalid
            }

            // When the ModelState is valid, proceed with the creation process
            var userId = _userIdProvider.GetUserId(); // Get user id from the provider
            var clientService = new ClientService(_context, _userIdProvider); // Create the ClientService with context and user id provider
            clientService.CreateBusiness(model);

            return RedirectToAction("Index");
        }




        [AllowAnonymous]
        public ActionResult Quote()
        {
            /*var svc = new FranchiseService();
            ViewBag.Franchises = svc.GetFranchises().Select(f => new
            {
                FranchiseId = f.FranchiseId,
                FranchiseName = f.FranchiseName
            }).ToList();*/

            return View();
        }


        [HttpPost]
        public ActionResult CalculateQuote(BusinessCreate quote)
        {
            foreach (var modelState in ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    System.Diagnostics.Debug.WriteLine($"Error: {error.ErrorMessage}");
                }
            }

            if (ModelState.IsValid)
            {
                // Create an instance of ClientService

                // Perform calculations using the PerformCalculations method
                var calculationResults = _clientService.PerformCalculations(quote);

                // Pass the calculation results to the Result view
                return View("Result", calculationResults);
            }
            else
            {
                ViewBag.Franchises = _franchiseService.GetFranchises().Select(f => new
                {
                    FranchiseId = f.FranchiseId,
                    FranchiseName = f.FranchiseName
                }).ToList();

                return View("Quote", quote);
            }
        }


        /*private double CalculateCO2Emission(double haulerEmissions, double smtEmissions)
        {
            double fuelConsumed = distance / (fuelEfficiency * 0.425143707); // Convert miles per gallon to liters per 100 km
            double co2Emission = fuelConsumed * emissionFactor;
            return co2Emission;
        }*/



        //GET: Details
        //Client/Details/{id}
        public ActionResult Details(int id)
        {
            var model = _clientService.GetBusinessById(id);
            //model.Invoices = _context.Invoices.Where(i => i.ClientId == id).ToList();

            return View(model);
        }




        //GET: Edit
        //Client/Edit/{id}
        public ActionResult Edit(int id)
        {
            var detail = _clientService.GetBusinessById(id);
            var model = new BusinessEdit
            {
                BusinessId = detail.BusinessId,
                BusinessName = detail.BusinessName,
                FacilityID = detail.FacilityID,
                State = detail.State,

BusinessMVC2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Smash Dashboard</title>
    <link rel="icon" href="~/Content/Images/favicon.ico" type="image/x-icon" />

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- jQuery UI -->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- DataTables CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">

    <!-- DataTables -->
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <!-- CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />

    <!-- Javascript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>



    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <meta name="robots" content="noindex">
</head>
<body id="diagonal-split-background" class="@(User.Identity.IsAuthenticated ? "logged-in" : "")">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Smash Dashboard", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (User.Identity.IsAuthenticated && User.Identity.Name.EndsWith("@smashmytrash.com"))
                    {
                        <li>@Html.ActionLink("Franchises", "Index", "Franchise")</li>
                        <li>@Html.ActionLink("Clients", "Index", "Client")</li>
                        <li>@Html.ActionLink("Updates", "Updates", "Home")</li>
                        if (User.Identity.IsAuthenticated && BusinessData.ValidEmails.NationalAccountsEmailList.Contains(User.Identity.Name))
                        {
                            <li>@Html.ActionLink("National Accounts", "Index", "NationalAccount")</li>
                        }

                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer id="footer">
            <p>&copy; @DateTime.Now.Year - Smash My Trash</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>